run:
	go run main.go \
	-password="1337" \
	-url="http://example.com" \
	-defaultWithArg="banana" \
	-active=true \
	-std-duration=1h30m \
	-std-time=2023-12-25T10:30:00Z \
	-duration=1d2h30m \
	-datetime=2023-12-25T10:30:00Z \
	-date=2023-12-25 \
	-unixtime=1703505000 \
	-float64=13.37 \
	-int=42
